from rest_framework import serializers
from adminsupport.models.EmployeeModels import EmployeeModel


class EmployeeSerializer(serializers.ModelSerializer):
    class Meta:
        model = EmployeeModel
        exclude = ['id']

    usid = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    employeeId = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    gender = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    firstName = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    lastName = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    email = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    company = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    division = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    function = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    department = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    section = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    subSection = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    departmentManager = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    parentDepartment = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    dob = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    designation = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    designationArabic = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    role = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    status = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    probationPeriod = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    doj = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    confirmationDate = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    endEmploymentDate = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    maritalStatus = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    nationality = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    nationalityArabic = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    approvalRuleLeave = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    approvalRuleExpense = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    approvalRuleTravel = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    approvalRuleWorkFromHome = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    approvalRuleProbation = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    visaNumber = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    visaIssueDate = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    visaExpiryDate = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    emiratesID = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    eidCardNumber = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    emiratesIDIssueDate = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    emiratesIDExpiryDate = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    uidNumber = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    uidIssueDate = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    uidExpiryDate = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    workLocation = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    employmentType = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    otherEmploymentType = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    importanceStatus = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    isArchived = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    isActive = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    annualLeaveEntitlement = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    annualLeaveTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    annualLeaveTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    carryOverAnnualLeaveEntitlement = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    carryOverAnnualLeaveTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    carryOverAnnualLeaveTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    sickLeaveEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    sickLeaveTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    sickLeaveTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    studyLeaveEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    studyLeaveTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    studyLeaveTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    maternityLeaveEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    maternityLeaveTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    maternityLeaveTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    paternityLeaveEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    paternityLeaveTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    paternityLeaveTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    compassionateLeaveEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    compassionateLeaveTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    compassionateLeaveTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    hajjLeaveEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    hajjLeaveTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    hajjLeaveTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    unpaidLeaveEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    unpaidLeaveTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    unpaidLeaveTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    compensatoryOffEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    compensatoryOffTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    compensatoryOffTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    outOfOfficeEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    outOfOfficeTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    outOfOfficeTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    remoteWorkEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    remoteWorkTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    remoteWorkTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    emergencyLeaveEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    emergencyLeaveTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    emergencyLeaveTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    longTermSickLeaveEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    longTermSickLeaveTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    longTermSickLeaveTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    daysInLieuEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    daysInLieuTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    daysInLieuTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    accompaniedLeaveInsideUAEEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    accompaniedLeaveInsideUAETotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    accompaniedLeaveInsideUAETaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    accompaniedLeaveOutsideUAEEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    accompaniedLeaveOutsideUAETotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    accompaniedLeaveOutsideUAETaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    nationalServiceEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    nationalServiceTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    nationalServiceTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    nationalServiceRefresherCourseEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    nationalServiceRefresherCourseTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    nationalServiceRefresherCourseTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    businessTripEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    businessTripTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    businessTripTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    trainingLeaveEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    trainingLeaveTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    trainingLeaveTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    exceptionalLeaveUAENationalsEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    exceptionalLeaveUAENationalsTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    exceptionalLeaveUAENationalsTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    permissionRequestEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    permissionRequestTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    permissionRequestTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    halfDaysLeaveEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    halfDaysLeaveTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    halfDaysLeaveTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    iddahLeaveEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    iddahLeaveTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    iddahLeaveTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    marriageLeaveEntitled = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    marriageLeaveTotal = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    marriageLeaveTaken = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    shiftType = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    shiftSubType = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    nameInArabic = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    positionCode = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    titlePerVisa = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    titlePerVisaInArabic = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    contactDetails = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    passportNumber = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    passportIssueDate = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    passportExpiryDate = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    noticePeriodForProbation = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    noticePeriodForConfirmed = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    visaOnCompany = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    mothersName = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    contactInformation = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    emergencyContactDetails = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    externalReferenceID = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    dependents = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    sponsor = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    decoded = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    grade = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    bcn = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    action = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    modified = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
