from rest_framework import serializers
from adminsupport.models.TimeAttendanceReportModel import TimeAttendanceReport


class TimeAttendanceSerializer(serializers.ModelSerializer):
    class Meta:
        model = TimeAttendanceReport
        fields = '__all__'

    Report_Date = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Day_of_the_Week = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Company = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Division = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Employee_ID = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Employee_Name = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Email_ID = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Designation = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Punch_In = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Punch_Out = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Actual_Duration = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Expected_Duration = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Temp_Expected_Duration = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Start_Location_Name = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    DIL = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Is_Force_Ended = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Method = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    End_Location_Name = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Remarks = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Correction_Reason = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Correction_Time_Start = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Correction_Time_End = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Correction_Comment = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Leave_Type = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Leave_Status = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Exceptions_Expected_Duration = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Travel_Type = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Business_Travel_Status = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    WFH_Status = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Department = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Function = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Section = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Shift_Type = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Shift_SubType = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Sub_Section = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    uuid = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Shift_Id = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Shift_Date = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Shift_Name = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Employee_Shift_Type = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Employee_Shift_SubType = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Shift_From = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Shift_To = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
    Modified_Date = serializers.CharField(
        required=False, allow_blank=True, allow_null=True)
